### ISSUE TITLE
Wired FN in A3

### ISSUE THREAD

**Issue by 9iang22** [DianQK/Tai-e-assignments-tips#1]
I have got 38/40 in lab3 and I find this 
https://github.com/pascal-lab/Tai-e-assignments/commit/1e718b4e89c25cdfe586eb2adaf9c90e7a333025
It says that the left value of an AssignStmt is not always a Var. (x
I think it can be added to the readme.

**Comment by dianqk** [comment]
@Mosk0ng Ha, we should be careful with type-forcing casting.

I will add the test case.
